# filepath: d:\final_devops\deployment\Helms\server\values.yaml
replicaCount: 1

image:
  repository: nithi1230/server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort # Changed from ClusterIP
  port: 5002

resources: {}
