replicaCount: 1

image:
  repository: nithi1230/server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5002
  nodePort: 30001  # 👈 Add this line to avoid hardcoding inside the template

resources: {}
