# filepath: d:\final_devops\deployment\Helms\Frontend\values.yaml
replicaCount: 1

image:
  repository: nithi1230/frontend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort 
  port: 80

resources: {}