apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5002
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30001
      {{- end }}
  selector:
    app: {{ include "server.fullname" . }}
