apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      nodePort: 30001
  selector:
    app: {{ include "server.fullname" . }}