apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index
        image: nithi1230/index:25  
        ports:
        - containerPort: 5001
