apiVersion: v1
kind: Service
metadata:
  name: {{ include "index.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5001
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30002 }}
      {{- end }}
  selector:
    app: {{ include "index.fullname" . }}
