apiVersion: v1
kind: Service
metadata:
  name: {{ include "index.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5004
      nodePort: 30002
  selector:
    app: {{ include "index.fullname" . }}